Piano di progetto - Preventivo e pianificazione sprint 2
6BitBusters/6BitBusters.github.io pull request #55
Opened 2024-11-27 18:14 UTC by edgarcarlos

- Stesura preventivo sprint 2
- Stesura pianificazione sprint 2

close #50

2024-11-28 19:53 UTC, EliaBergamin requested changes
Per qualche motivo non viene superato il test di compilazione

2024-11-28 19:53 UTC, EliaBergamin commented on Docs/Generali/piano_di_progetto/03_pianificazione.tex
> +     Durante questo secondo sprint, ci dedicheremo alla raccolta e all'analisi dei requisiti, identificando i casi d'uso. Questi saranno documentati nel file \textit{"Analisi dei requisiti"} per gara
Infine

2024-11-28 19:53 UTC, EliaBergamin commented on Docs/Generali/piano_di_progetto/03_pianificazione.tex
> +            \label{fig:3.1} % Etichetta per il riferimento
3.2

2024-11-28 21:00 UTC, edgarcarlos commented on Docs/Generali/piano_di_progetto/03_pianificazione.tex
> +     Durante questo secondo sprint, ci dedicheremo alla raccolta e all'analisi dei requisiti, identificando i casi d'uso. Questi saranno documentati nel file \textit{"Analisi dei requisiti"} per gara
fatto

2024-11-28 21:01 UTC, edgarcarlos commented on Docs/Generali/piano_di_progetto/03_pianificazione.tex
> +            \label{fig:3.1} % Etichetta per il riferimento
fatto

2024-11-30 10:35 UTC, EliaBergamin approved these changes

2024-11-30 10:36 UTC, merged