Piano di progetto - 42
6BitBusters/6BitBusters.github.io pull request #60
Opened 2024-11-29 20:50 UTC by edgarcarlos

Stesura consuntivo sprint 1

close #42

2024-11-30 14:51 UTC, EliaBergamin requested changes

2024-11-30 14:51 UTC, EliaBergamin commented on Docs/Generali/piano_di_progetto/05_consuntivo.tex
> +causate dalla nostra inesperienza nella stima accurata dei tempi necessari per le attività.
Frase ripetitiva, la toglierei.
Tra l'altro, la causa principale è stato il parziale di calcolo che ha sottratto tempo ad alcuni membri del gruppo.

2024-11-30 14:51 UTC, EliaBergamin commented on Docs/Generali/piano_di_progetto/05_consuntivo.tex
> +Per gli sprint successivi, sarà necessario affinare la fase di preventivo, valutando con
fase di preventivazione

2024-11-30 22:35 UTC, edgarcarlos commented on Docs/Generali/piano_di_progetto/05_consuntivo.tex
> +causate dalla nostra inesperienza nella stima accurata dei tempi necessari per le attività.
ahh si , non l'avevo notato la ripetizione

2024-12-01 09:17 UTC, EliaBergamin approved these changes

2024-12-01 09:18 UTC, merged