VE_2024-11-28 - 57
6BitBusters/6BitBusters.github.io pull request #61
Opened 2024-11-29 21:13 UTC by edgarcarlos

Redazione verbale esterno del 28-11-2024

Close #57

2024-11-30 11:05 UTC, EliaBergamin requested changes

2024-11-30 11:05 UTC, EliaBergamin commented on Docs/Verbali Esterni/VE_2024-11-28/config/tracking_input.tex
> +
Cerca di essere più specifico, ad esempio:
4.1 Aggiungere caso d'uso per gli errori
4.2 Aggiungere c.u. per tornare indietro (non scritto così, ovviamente)
4.3 ...

2024-11-30 21:57 UTC, edgarcarlos commented on Docs/Verbali Esterni/VE_2024-11-28/config/tracking_input.tex
> +
okk

2024-12-01 08:52 UTC, EliaBergamin approved these changes

2024-12-01 08:59 UTC, merged