Analisi dei requisiti - 44 (Pincin)
6BitBusters/6BitBusters.github.io pull request #63
Opened 2024-12-04 15:14 UTC by MPincin

Descritti i casi d'uso contenuti nel documento condiviso, dal numero 1 al 7

2024-12-04 17:16 UTC, EliaBergamin requested changes

2024-12-05 05:58 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +        \item Il sistema dispone di un elenco di API disponibili da mostrare.
Questa non mi sembra una precondizione. Piuttosto mi sembra una caratteristica che il sistema deve avere a prescindere.

2024-12-05 06:00 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +        \item Il sistema è in grado di trasformare il dataset in una rappresentazione tabellare.
Anche questa non mi sembra una precondizione. Piuttosto mi sembra una caratteristica che il sistema deve avere a prescindere.

2024-12-05 06:01 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +        \item Il sistema dispone delle informazioni necessarie per generare un grafico a istogramma.
Anche queste ultime due non mi sembrano una precondizione. Se il dataset è caricato correttamente, le altre due sono ovvie.

2024-12-05 06:08 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +        \item Il sistema ha accesso ai dettagli tecnici e descrittivi delle API.
Con questo si intende che riesco a connettermi al db o al servizio esterno?

2024-12-05 06:24 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +\subsection{UC4 - Visualizzazione assi}
Questo è un sottocaso della visualizzazione del grafico

2024-12-05 06:24 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +\subsection{UC5 - Visualizzazione legenda}
Questo è un sottocaso della visualizzazione del grafico

2024-12-05 06:27 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/template/images/UC1.1_1.1.1_1.1.2_1.1.3.png
Relazione di inclusione tra 1.1 e 1.1.1, 1.1.2,1.1.3

2024-12-05 06:28 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/template/images/UC4.png
Relazione di inclusione tra UC4 e UC3

2024-12-05 06:28 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/template/images/UC5.png
Relazione di inclusione tra UC5 e UC3

2024-12-05 11:11 UTC, MPincin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +        \item Il sistema ha accesso ai dettagli tecnici e descrittivi delle API.
Intendo dire che i dettagli effettivamente esistano, nel senso che sia nel caso siano reperiti direttamente dall'api che nel caso siano caricati da noi, esista un nome, una dimensione e una descrizione del dataset

2024-12-05 16:31 UTC, EliaBergamin requested changes

2024-12-05 16:31 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +        \item Un dataset è stato caricato correttamente.
Un dataset -> Il dataset selezionato (anche sotto)

2024-12-05 16:31 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
>      \item \begin{itemize}
togliere \item

2024-12-05 16:31 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
>      \item \begin{itemize}
togliere \item

2024-12-05 16:31 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \begin{itemize}
Non volermene, ma date le precondizioni, non serve indicare le azioni iniziali:
\item L’utente visualizza il grafico 3D nell’interfaccia;
\item L'utente visualizza gli assi X,Y e Z.

2024-12-06 11:39 UTC, EliaBergamin requested changes

2024-12-06 11:39 UTC, EliaBergamin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \item \textbf{Attore:} Utente;
minuscola dopo i :
(correggere anche sotto)

2024-12-06 15:41 UTC, MPincin commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \caption{UC1 - Visualizzazione lista dei dataset disponibili}
c'è un comando chiamato \listoffigures, l'ho messo nel main e crea la lista in automatico prendendo le caption

2024-12-06 16:14 UTC, EliaBergamin approved these changes

2024-12-06 16:20 UTC, merged