Analisi dei requisiti - 44 (Diviesti)
6BitBusters/6BitBusters.github.io pull request #66
Opened 2024-12-05 21:05 UTC by FilippoDiviesti

Stesura casi d'uso da UC8 a UC14

2024-12-06 15:24 UTC, AndreaSoranzo requested changes
Rivedere:

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item La telecamera e la sua inquadratura si trovano in una posizione corrispondente a quella iniziale cioè quando l'ambiente 3D era appena stato inizializzato.
Scriverei:
La posizione e angolazione della telecamera corrispondono alla configurazione di iniziale, uguale a quella di inizializzazione dell'ambiente 3D.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item L'utente interagisce con l'interfaccia per ripristinare la posizione della telecamera e la relativa inquadratura ai valori iniziali.
Scriverei:
L'utente interagisce con l'interfaccia per ripristinare la posizione e angolazione della telecamera ai valori iniziali.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \item \textbf{Descrizione:} L'utente, tramite interazione opportuna, può selezionare una barra del grafico all'interno dell'ambiente 3D.
Scriverei:
 L'utente può selezionare una barra del grafico 3D.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item L'utente interagisce con l'interfaccia e compie un'azione di selezione che viene evidenziata nella tabella.
Scriverei:
L'utente interagisce con il grafico 3D, evidenziando la corrispondente cella della tabella.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \item \textbf{Descrizione:} L'utente, tramite interazione opportuna, può selezionare una cella all'interno della tabella.
Scriverei:
L'utente può selezionare una cella all'interno della tabella.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Viene evidenziata la selezione sia della cella della tabella selezionata sia della corrispetiva barra del grafico all'interno dell'ambiente 3D.
Scriverei:
Viene evidenziata cella della tabella.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item L'utente interagisce con la tabella selezionando una cella.
Scriverei:
L'utente interagisce con la tabella selezionando una cella la quale verrà evidenziata.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \item \textbf{Descrizione:} Viene evidenziata in maniera opportuna nel grafico all'interno dell'ambiente 3D la selezione compiuta dall'utente.
Scriverei:
Viene evidenziata in maniera opportuna nel grafico 3D la selezione compiuta dall'utente nella tabella.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Viene evidenziata la selezione nel grafico all'interno dell'ambiente 3D.
Scriverei:
Viene evidenziata della barra del grafico 3D.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item L'utente interagisce con l'interfaccia e compie un'azione di selezione che viene evidenziata nel grafico all'interno dell'ambiente 3D.
Scriverei:
L'utente interagisce con una cella della tabella, evidenziando la corrispondente barra del grafico 3D.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \item \textbf{Descrizione:} La posizione della telecamera e l'inquadratura vengono posizinate in maniera consona in modo tale da ottenere in primo piano uno specifico oggetto all'interno dell'amb
Scriverei:
In seguito alla selezione di una cella, la vista si sposta sulla corrispondente barra del grafico 3D, centrandola sullo schermo.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item La telecamera e la relativa inquadratura saranno in una posizione diversa da quella iniziale e avranno inoltre in primo piano uno specifico oggetto dell'ambiente 3D.
Scriverei:
La telecamera e la relativa inquadratura saranno in una posizione diversa da quella iniziale e avranno inoltre in primo piano la barra selezionata del grafico 3D.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +\subsection{UC12: Opacizzare barra del grafico}
Scriverei:
Modifica trasparenza barra del grafico

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \caption{UC12: Opacizzare barra del grafico}
Scriverei:
Modifica trasparenza barra del grafico

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Il valore di opacità di una barra del grafico nell'ambiente 3D è maggiore rispetto al valore iniziale.
Scriverei:
 Il valore di trasparenza delle altre barre del grafico 3 3D è maggiore rispetto a quello delle altre.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Per evidenziare una determinata barra del grafico vengono opacizzate tutte le altre.
Scriverei:
L'utente evidenzia una determinata barra del grafico viene aumentato il valore di trasparenza a tutte le altre.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +\subsubsection{UC12.1: Opacizzare le barre rispetto a valori superiori o inferiori}
Scriverei:
Rendere più visibili solo le barre rispetto a valori superiori o inferiori

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \item \textbf{Descrizione:} L'utente interagisce opportunamente con l'interfaccia impostando un valore rispetto al quale ogni barra con valore superiore o inferiore (parametro specificato dall'ut
Scriverei:
L'utente può stabilire un valore limite al di sopra o al di sotto del quale alcune barre verranno evidenziate.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Ogni barra con il rispettivo valore che non rispetta le condizioni poste dall'utente verrà opacizzata.
Scriverei:
Ogni barra selezionata nel grafico 3D viene resa più visibile rendendo le altre barre più trasparenti.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item L'utente interagisce con l'interfaccia per evidenziare nel grafico all'interno dell'ambiente 3D solo le barre con un valore superiore/inferiore a quello indicato.
Scriverei:
L'utente interagisce con l'interfaccia selezionando il numero di barre con i valori più elevati o più bassi da evidenziare nel grafico 3D.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +\subsubsection{UC12.2: Lasciare visibili solo le prime/ultime X barre}
Scriverei:
Rendere più visibili solo le prime/ultime X barre

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \item \textbf{Descrizione:} L'utente può evidenziare le X barre più piccole/grandi.
Scriverei:
 L'utente può selezionare quante barre con i valori più elevati o più bassi evidenziare.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Ogni barra del grafico nell'ambiente 3D con il rispettivo valore che non rientra nei primi X valori più piccoli/grandi viene opacizzata.
Scriverei:
Ogni barra selezionata nel grafico 3D viene resa più visibile rendendo le altre barre più trasparenti.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item L'utente interagisce con l'interfaccia per evidenziare nel grafico all'interno dell'ambiente 3D le prime X barre con il corrispettivo valore che rientra nei primi X valori più picco
Scriverei:
 L'utente interagisce con l'interfaccia selezionando il numero di barre con i valori più elevati o più bassi da evidenziare nel grafico 3D.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +\subsubsection{UC12.3: Opacizzare le barre con i valori superiori/inferiori al valore medio}
Scriverei:
Rendere più visibili le barre con i valori superiori/inferiori al valore medio

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +    \item \textbf{Descrizione:} L'utente interagisce opportunamente con l'interfaccia per opacizzare ogni barra del grafico all'interno dell'ambiente 3D con il rispettivo valore superiore/inferiore a
Scriverei:
L'utente può scegliere se evidenziare nel grafico 3D le barre il quale valore è superiore o inferiore al valore medio.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Ogni barra con il rispettivo valore superiore/inferiore al valore medio verrà opacizzata.
Scriverei:
Ogni barra selezionata del grafico 3D viene resa più visibile rendendo le altre barre più trasparenti.

2024-12-06 15:24 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item L'utente interagisce con l'interfaccia per evidenziare nel grafico all'interno dell'ambiente 3D solo le barre con un valore superiore/inferiore al valore medio.
Scriverei:
L'utente interagisce con l'interfaccia per evidenziare nel grafico 3D solo le barre con un valore superiore o inferiore al valore medio.

2024-12-06 15:37 UTC, AndreaSoranzo commented
Rivedere in generale i nomi dei casi d'uso. Si devono capire subito solo dai nomi

2024-12-06 17:48 UTC, AndreaSoranzo commented
Sistema i conflitti

2024-12-10 08:24 UTC, FilippoDiviesti commented
> Non tutte le request changes sono state discusse/implementate

Tutte le changes sono state implementate

2024-12-10 08:40 UTC, FilippoDiviesti commented
Risolti i conflitti

2024-12-10 16:21 UTC, AndreaSoranzo approved these changes

2024-12-10 16:24 UTC, merged