Piano di qualifica - 47
6BitBusters/6BitBusters.github.io pull request #76
Opened 2024-12-11 18:24 UTC by EliaBergamin

Aggiunta sezione Qualità di processo
close #47

2024-12-11 20:43 UTC, ElenaaaCh commented on Docs/Generali/piano_di_qualifica/02_qual_di_proc.tex
> +Per il miglioramento continuo nella qualità dei
della qualità

2024-12-11 21:04 UTC, ElenaaaCh commented on Docs/Generali/piano_di_qualifica/02_qual_di_proc.tex
> +     Registra le informazioni prodotte da un processo o da un'attività del ciclo di vita &
Aggiungi: controllo che i documenti prodotti siano facilmente comprensibili

2024-12-11 21:05 UTC, ElenaaaCh commented on Docs/Generali/piano_di_qualifica/02_qual_di_proc.tex
> +     Fornisce una garanzia adeguata che i prodotti software e i processi del
Change: Fornisce garanzia adeguata -> Garantisce

2024-12-11 21:07 UTC, ElenaaaCh commented on Docs/Generali/piano_di_qualifica/02_qual_di_proc.tex
> +     Definisce, organizza, monitora e conclude le attività &
add: le attività di un processo

2024-12-11 21:17 UTC, ElenaaaCh requested changes
Sistemare le frasi indicate

2024-12-12 09:30 UTC, EliaBergamin commented on Docs/Generali/piano_di_qualifica/02_qual_di_proc.tex
> +     Registra le informazioni prodotte da un processo o da un'attività del ciclo di vita &
La comprensibilità del testo (indice Gulpease) la aggiungerei come metrica del prodotto. Qui devo misurare il processo di documentazione, non il prodotto.

2024-12-13 13:14 UTC, ElenaaaCh submitted a review, later dismissed

2024-12-13 15:16 UTC, ElenaaaCh approved these changes

2024-12-13 15:16 UTC, merged