Analisi dei Requisiti - 70
6BitBusters/6BitBusters.github.io pull request #77
Opened 2024-12-11 20:20 UTC by AndreaSoranzo

- Aggiunta la sezione relativa ai requisiti
close #70

2024-12-11 22:41 UTC, edgarcarlos commented on Docs/Generali/analisi_dei_requisiti/03_requisiti.tex
> +    RF12 & Il Sistema modifica la trasparenza delle barre del grafico & Obbligatorio & UC12 \tabularnewline
Direi : l'utente deve poter gestire la trasparenza delle barre del grafico

2024-12-11 22:42 UTC, edgarcarlos commented on Docs/Generali/analisi_dei_requisiti/03_requisiti.tex
> +    RF12.2 & L’utente deve poter sceglere un numero "X" che verra` utilizzato per rendere piu` trasparenti le barre, i quali valori non rientrano tra i primi o ultimi X & Obbligatorio & UC12.2 \tabul
scegliere

2024-12-11 22:44 UTC, edgarcarlos commented on Docs/Generali/analisi_dei_requisiti/03_requisiti.tex
> +    RF13 & L’utente deve poter sceglere visualizzare il piano parallelo alla base che rappresenta il valor medio globale & Obbligatorio & UC13 \tabularnewline
Occorenza di sceglere a posto di scegliere

2024-12-11 22:47 UTC, edgarcarlos commented on Docs/Generali/analisi_dei_requisiti/03_requisiti.tex
> +    RF13 & L’utente deve poter sceglere visualizzare il piano parallelo alla base che rappresenta il valor medio globale & Obbligatorio & UC13 \tabularnewline
Direi: L’utente deve poter scegliere di visualizzare . . .

2024-12-11 22:52 UTC, edgarcarlos requested changes
Vale per tutta la sezione: c'è un problema con gli accenti
a' --> à
e' --> è
(forse viene dal tuo OS )

2024-12-11 23:14 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/03_requisiti.tex
> +    RF12 & Il Sistema modifica la trasparenza delle barre del grafico & Obbligatorio & UC12 \tabularnewline
Non credo sia l'utente che gestisce quanta trasparenza applicare

2024-12-11 23:15 UTC, AndreaSoranzo commented on Docs/Generali/analisi_dei_requisiti/03_requisiti.tex
> +    RF13 & L’utente deve poter sceglere visualizzare il piano parallelo alla base che rappresenta il valor medio globale & Obbligatorio & UC13 \tabularnewline
Non ho capito

2024-12-12 08:43 UTC, edgarcarlos commented on Docs/Generali/analisi_dei_requisiti/03_requisiti.tex
> +    RF13 & L’utente deve poter sceglere visualizzare il piano parallelo alla base che rappresenta il valor medio globale & Obbligatorio & UC13 \tabularnewline
errore di battitura : Hai messo "sceglere" al posto di "scegliere" più volte

2024-12-12 09:06 UTC, edgarcarlos commented on Docs/Generali/analisi_dei_requisiti/03_requisiti.tex
> +    RF12 & Il Sistema modifica la trasparenza delle barre del grafico & Obbligatorio & UC12 \tabularnewline
ok ho capito, mi sono basato sulla use case visto che l'attore è l'utente. Comunque così mi sembra come se fosse una gestione automatica della trasparenza

Per chiarezza direi : Il sistema modifica la trasparenza delle barre del grafico secondo azioni dell'utente

2024-12-12 21:39 UTC, edgarcarlos submitted a review, later dismissed

2024-12-23 15:21 UTC, edgarcarlos approved these changes
verificato

2024-12-23 15:24 UTC, merged