change: aggiunti i contatori automatici ai casi d`uso
6BitBusters/6BitBusters.github.io pull request #84
Opened 2024-12-15 16:35 UTC by AndreaSoranzo

- Aggiunti dei nuovi comandi per auto-numerare i casi d`uso
close #78

2024-12-15 16:53 UTC, ElenaaaCh commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Le informazioni sul dataset vengono mostrate all'utente.
del dataset

2024-12-15 16:53 UTC, ElenaaaCh commented on Docs/Generali/analisi_dei_requisiti/02_use_cases.tex
> +            \item Il sistema ha accesso alle informazioni sul dataset.
del dataset

2024-12-15 16:58 UTC, ElenaaaCh requested changes
Attenzione:
sistemare le frasi contenenti "sul dataset" con proposizione come del o nel
togliere le righe vuote superflue (675-677, 761-763, ...)

2024-12-15 17:04 UTC, AndreaSoranzo commented
> Attenzione: sistemare le frasi contenenti "sul dataset" con proposizione come del o nel togliere le righe vuote superflue (675-677, 761-763, ...)

gli spazi vuoti verranno rimossi una volta finiti per bene i casi d`uso vista la difficolta nel distinguere quando le varie sezioni iniziano e terminano

2024-12-16 07:30 UTC, ElenaaaCh approved these changes

2024-12-16 07:32 UTC, merged